### PR TITLE
Malotho/making actorstestable

### PR DESCRIPTION
**Pull request by malotho**
# Description

https://github.com/dapr/dotnet-sdk/pull/220#issuecomment-586623718
This is a fix to the null reference exception which was caused by an incorrect actor dependency assignment order.

## Issue reference

This is in relation to issue #173

### CODE REVIEW

**Comment by yaron2** [comment]
cc @amanbha

**Comment by amanbha** [comment]
@malotho Thanks for fixing the initialization order. Could you please update your branch as well before the merge.

**Comment by malotho** [comment]
@amanbha I will merge the branches and let you know when done. Thanks

**Comment by malotho** [comment]
@amanbha @yaron2

**Comment by yaron2** [comment]
Thanks!

**Pull request merged**
