### PR TITLE
Remove unused using statements.

### PR DESCRIPTION
**Pull request by RafaelJCamara**
# Description
Remove unused using statements.

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [X] Code compiles correctly
* [ ] Created/updated tests
* [ ] Extended the documentation

### CODE REVIEW

**Comment by m3nax** [comment]
@RafaelJCamara Can you sign DCO? It's the only action that fails

```
git rebase HEAD~1 --signoff
git push --force-with-lease origin remove-usings
```

**Comment by WhitWaldo** [comment]
@RafaelJCamara Thank you for your contribution!

I merged the latest from master in your branch and it's showing a number of build/test failures. As you've got the time for it, I'd appreciate it if you could remedy whatever has broken here as a result of the changes. Once it's all passing, please ping me with a notification and I'd be happy to accept and merge your PR.

**Comment by RafaelJCamara** [comment]
@WhitWaldo Merge conflicts solved.

**Review by WhitWaldo — APPROVED** [review]
Looks good. Thank you for your contribution!

**Pull request merged**
