### PR TITLE
Upgrade Specific compile against .NETCORE 3.1, NET6, NET7

### PR DESCRIPTION
**Pull request by bobbyangers**
# Description

I have added the specific compilation profile/result for `.net5`, `.net6` and `.net7` and updated the various nuget to compile against the latest in each.

## Issue reference

We strive to have all PR being opened based on an issue, where the problem or feature have been discussed prior to implementation.

Please reference the issue this PR will close: #985 

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [x] Created/updated tests
* [x] Extended the documentation  (N/A)

### CODE REVIEW

**Comment by bobbyangers** [comment]
Hi, Anytning I can do to help?

**Comment by yaron2** [comment]
cc @rynowak @halspang

**Comment by bobbyangers** [comment]
Hi guys,

Sorry, since branch fell behind, I merged master into my branch and waiting for your approval again.

cc @rynowak @halspang

**Comment by WhitWaldo** [comment]
Hello @bobbyangers and thank you for your contribution!

Unfortunately, I'm not going to accept this PR simply because we're moving ahead to newer .NET versions. As of 1.14, the .NET SDK targets only .NET 6 and .NET 8 (though Workflow targets .NET 7). As part of the 1.15 release, we'll continue to target .NET 6, but as a "deprecated" release. We'll continue to maintain support for .NET 8 and should the release schedules align, we anticipate adding .NET 9 as a supported target, dropping the .NET 6 target/testing with 1.16.

**Pull request closed without merging**
