### PR TITLE
Added DeleteBulkState operation to dotnet sdk

### PR DESCRIPTION
**Pull request by jigargandhi**
# Description

Added bulk delete operation to dotnet-sdk

## Issue reference

We strive to have all PR being opened based on an issue, where the problem or feature have been discussed prior to implementation.

Please reference the issue this PR will close: https://github.com/dapr/dapr/issues/2658

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [x] Created/updated tests
* [ ] Extended the documentation

### CODE REVIEW

**Comment by jigargandhi** [comment]
@rynowak please review this

**Comment by jigargandhi** [comment]
@vinayada1 please review this

**Comment by rynowak** [comment]
Has this landed in the Dapr runtime? Is this part of 1.0 or 1.1?

**Comment by jigargandhi** [comment]
Yes, this was added in runtime with PR https://github.com/dapr/dapr/pull/2660

**Review by rynowak — APPROVED** [review]
This is great! Thanks.

**Pull request merged**
