### PR TITLE
Register Dapr services in keyed-compatible manner

### PR DESCRIPTION
**Pull request by philliphoff**
# Description

.NET 8 adds the ability to register "keyed" services with a service collection. The implementation of this feature, however, breaks how many existing components look through that service collection to determine whether they've been previously registered (a common if, perhaps, now an anti-pattern with the advent of `TryAddSingleton()`).  If a component registers a keyed service *before* another component performs such a search, that search cause an exception to be thrown.

The Dapr .NET SDK uses this "old" style of registering "marker" services to help prevent multiple registrations, which triggers this new behavior in .NET 8.  This change switches to the newer `TryAddSingleton()` approach to avoid that problem.  

## Issue reference

We strive to have all PR being opened based on an issue, where the problem or feature have been discussed prior to implementation.

Please reference the issue this PR will close: #1235 

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [x] Created/updated tests
* [ ] Extended the documentation

### CODE REVIEW

**Comment by philliphoff** [comment]
@halspang Would appreciate a quick review when you have a chance, thanks!

**Comment by rliberoff** [comment]
Hello!

I hope this helps: from further investigation, we found out that the offending dependency is with library `Microsoft.Extensions.Http.Resilience` when updated from version `8.1.0` to `8.2.0`. Hope it helps.

When using that library, the `AddDaprClient` throws the exception that is mentioned in the issue.

My Team and I really appreciete your effor guys for providing an update for this. Thank you.

**Review by halspang — APPROVED** [review]

**Comment by onionhammer** [comment]
When is this getting released (non-preview)?

**Comment by philliphoff** [comment]
> When is this getting released (non-preview)?

@onionhammer It will be released as part of the larger Dapr 1.13 release, coming very soon.

**Pull request merged**
