### PR TITLE
Fixing nuspec for nuget generation.

### PR DESCRIPTION
**Pull request by amanbha**
# Description

Fixing nuspec for nuget generation.

Fixes https://github.com/dapr/dotnet-sdk/issues/112

### CODE REVIEW

**Comment by loic-sharma** [comment]
Out of curiosity @amanbha, why is Dapr using nuspec to generate .nupkg files? Is there something preventing you from packing  packages using the .csproj instead? For more information, please refer to:

* https://docs.microsoft.com/en-us/nuget/create-packages/creating-a-package-dotnet-cli
* https://docs.microsoft.com/en-us/dotnet/core/tools/csproj#nuget-metadata-properties

**Comment by amanbha** [comment]
@loic-sharma  Nuspec allows more control and flexibility on how and where you want to put files, (we are putting icon files in the pkg itself) and provides more control specially if you decide to put multiple dlls form different projects into one nuget pkg.

**Comment by loic-sharma** [comment]
> @loic-sharma Nuspec allows more control and flexibility on how and where you want to put files, (we are putting icon files in the pkg itself) 

Packing from a .nuspec is more flexible, but it is also significantly harder. NuGet has conventions for things like asset compatibility, you will continuously run into issues if you choose to manually pack with a .nuspec. Also, it is possible to [pack arbitrary files](https://docs.microsoft.com/en-us/nuget/reference/msbuild-targets#including-content-in-a-package) and or to [embed icons](https://docs.microsoft.com/en-us/nuget/reference/msbuild-targets#packing-an-icon-image-file) using .csproj.

> and provides more control specially if you decide to put multiple dlls form different projects into one nuget pkg.

Out of curiousity, why do you need this? I believe you can do this too by [including the assets from your project references](https://docs.microsoft.com/en-us/nuget/reference/msbuild-targets#project-to-project-references). This seems like a weird scenario though...

**Comment by amanbha** [comment]
@loic-sharma yes, simplicity is there with .csproj, we picked flexible over simple. We will definatley change it if we run into further issues.

**Pull request merged**
