### PR TITLE
preserve comparer of the original dictionary

### PR DESCRIPTION
**Pull request by tomhreb**
Signed-off-by: Tomas Hrebicek <tomhreb@users.noreply.github.com>

# Description

Fixes issue #934 

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [ ] Created/updated tests
* [ ] Extended the documentation

### CODE REVIEW

**Comment by halspang** [comment]
@tomhreb - Thanks for opening this! I'm a little bit worried about removing case sensitivity though. What if people are depending on that?

I think this may be more what you're looking for #887?

**Comment by tomhreb** [comment]
@halspang No, I don't think #887 is related.

Without the case sensitivity, this functionality does not work. The original dictionary in the .net core library has this case sensitivity. I still regard this as a bugfix.

**Comment by tomhreb** [comment]
Hi @halspang, any idea if this will be approved?

Check that the base class in .net SDK really has ```StringComparer.OrdinalIgnoreCase```.

https://github.com/dotnet/dotnet/blob/b8bc661a7429baa89070f3bee636b7fbc1309489/src/runtime/src/libraries/Microsoft.Extensions.Configuration/src/ConfigurationProvider.cs

**Comment by WhitWaldo** [comment]
I agree that this is a bugfix. I've flagged it as a breaking change as it might indeed break some people that are using it, but I agree that the code in `DaprConfigurationStoreProvider` is flawed here in that it's taking a `Dictionary<string,string>(StringComparer.OrdinalIgnoreCase)` and then doing update operations on a `Dictionary<string,string>()` that it's then setting the original implementation to which is not right.

@tomhreb Once all the tests finish running against it, I'll merge this. Thank you for your contribution!

**Review by WhitWaldo — APPROVED** [review]
Solid bugfix. Looks good to me!

**Pull request merged**
